# Site settings
title: Neo-17
email: antonios1789@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Programación y tecnología.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Rey-17

# Build settings
markdown: kramdown
